#!/usr/bin/env python3
"""Generate native FreeCAD artifacts for the Lamina Slender Wooden Biped v4.

Run with FreeCAD's Python runtime, not ordinary system Python:

    /Applications/FreeCAD.app/Contents/Resources/bin/freecadcmd generate_lamina_v4.py

The generated geometry is architecture-grade: useful for proportions, module
interfaces, clearances, visualization, and iteration. It is not a validated
structural design or a release-to-fabrication package.
"""

from __future__ import annotations

import math
import os

import FreeCAD as App
import Part


HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "generated")
os.makedirs(OUT, exist_ok=True)

WOOD = (0.78, 0.55, 0.30)
WOOD_LIGHT = (0.92, 0.76, 0.50)
WOOD_EDGE = (0.48, 0.28, 0.12)
CHARCOAL = (0.10, 0.13, 0.15)
STEEL = (0.52, 0.55, 0.57)
RUBBER = (0.035, 0.045, 0.05)
RED = (0.82, 0.04, 0.03)
YELLOW = (0.95, 0.68, 0.04)
BLUE = (0.18, 0.38, 0.52)


def set_view(obj, color, transparency=0):
    try:
        obj.ViewObject.ShapeColor = color
        obj.ViewObject.LineColor = tuple(max(0.0, c * 0.55) for c in color)
        obj.ViewObject.Transparency = transparency
    except Exception:
        pass


def solid_features(doc):
    """Return only authored solid features, excluding App::Part/Origin containers."""
    result = []
    for obj in doc.Objects:
        if obj.TypeId != "Part::Feature":
            continue
        shape = getattr(obj, "Shape", None)
        if shape is None or shape.isNull() or len(shape.Solids) == 0:
            continue
        if not shape.BoundBox.isValid():
            continue
        result.append(obj)
    return result


def add_feature(doc, group, name, label, shape, color, transparency=0):
    # Plain Part::Feature objects reopen visibly even when generated by
    # FreeCADCmd without GuiDocument.xml. PartDesign::Feature objects created
    # headlessly can be treated as hidden/suppressed by the GUI.
    obj = doc.addObject("Part::Feature", name)
    obj.Label = label
    obj.Shape = shape
    set_view(obj, color, transparency)
    if group is not None:
        group.addObject(obj)
    return obj


def polygon_face(points):
    pts = [App.Vector(*p) for p in points]
    pts.append(pts[0])
    return Part.Face(Part.makePolygon(pts))


def ellipse_face(cx, cy, z, rx, ry, segments=72):
    points = []
    for i in range(segments):
        a = 2.0 * math.pi * i / segments
        points.append((cx + rx * math.cos(a), cy + ry * math.sin(a), z))
    return polygon_face(points)


def ellipse_ring(cx, cy, z, rx, ry, thickness, ring_width):
    outer = ellipse_face(cx, cy, z, rx, ry)
    inner = ellipse_face(cx, cy, z, max(2, rx - ring_width), max(2, ry - ring_width))
    return outer.cut(inner).extrude(App.Vector(0, 0, thickness))


def tapered_solid_z(cx, cy, z0, z1, w0, d0, w1, d1):
    lower = polygon_face([
        (cx - w0 / 2, cy - d0 / 2, z0),
        (cx + w0 / 2, cy - d0 / 2, z0),
        (cx + w0 / 2, cy + d0 / 2, z0),
        (cx - w0 / 2, cy + d0 / 2, z0),
    ]).OuterWire
    upper = polygon_face([
        (cx - w1 / 2, cy - d1 / 2, z1),
        (cx + w1 / 2, cy - d1 / 2, z1),
        (cx + w1 / 2, cy + d1 / 2, z1),
        (cx - w1 / 2, cy + d1 / 2, z1),
    ]).OuterWire
    return Part.makeLoft([lower, upper], True, False)


def hollow_tapered_link(cx, cy, z0, z1, w0, d0, w1, d1, wall=9):
    outer = tapered_solid_z(cx, cy, z0, z1, w0, d0, w1, d1)
    inset = max(wall, 6)
    inner = tapered_solid_z(
        cx,
        cy,
        z0 + wall,
        z1 - wall,
        max(8, w0 - 2 * inset),
        max(8, d0 - 2 * inset),
        max(8, w1 - 2 * inset),
        max(8, d1 - 2 * inset),
    )
    return outer.cut(inner)


def hollow_box(cx, cy, z, width, depth, height, wall=9):
    outer = Part.makeBox(width, depth, height, App.Vector(cx - width / 2, cy - depth / 2, z))
    inner = Part.makeBox(
        max(2, width - 2 * wall),
        max(2, depth - 2 * wall),
        max(2, height - 2 * wall),
        App.Vector(cx - width / 2 + wall, cy - depth / 2 + wall, z + wall),
    )
    return outer.cut(inner)


def cylinder_y(cx, cy, cz, radius, depth):
    return Part.makeCylinder(radius, depth, App.Vector(cx, cy - depth / 2, cz), App.Vector(0, 1, 0))


def cylinder_x(cx, cy, cz, radius, depth):
    return Part.makeCylinder(radius, depth, App.Vector(cx - depth / 2, cy, cz), App.Vector(1, 0, 0))


def cylinder_between(p0, p1, radius):
    start = App.Vector(*p0)
    end = App.Vector(*p1)
    delta = end.sub(start)
    return Part.makeCylinder(radius, delta.Length, start, delta)


def add_joint(doc, wood_group, hardware_group, actuator_group, name, x, y, z, radius, depth):
    shell = cylinder_y(x, y, z, radius, depth)
    bore = cylinder_y(x, y, z, max(5, radius * 0.56), depth + 4)
    add_feature(doc, wood_group, name + "Housing", name.replace("_", " ") + " wooden housing", shell.cut(bore), WOOD)
    add_feature(doc, actuator_group, name + "Actuator", name.replace("_", " ") + " actuator envelope", cylinder_y(x, y, z, radius * 0.48, depth * 0.82), CHARCOAL)
    add_feature(doc, hardware_group, name + "Shaft", name.replace("_", " ") + " standard shaft", cylinder_y(x, y, z, max(4, radius * 0.13), depth + 14), STEEL)


def add_robot_parameters(doc):
    p = doc.addObject("App::FeaturePython", "DesignParameters")
    p.Label = "Lamina v4 design parameters — rerun generator after editing"
    for prop, label, value in [
        ("RobotHeight", "Nominal robot height", 1500.0),
        ("PlywoodThin", "Thin plywood", 6.0),
        ("PlywoodStructural", "Structural plywood", 12.0),
        ("LinkWall", "Torsion-box wall", 9.0),
        ("TorsoWidth", "Torso width", 400.0),
        ("TorsoDepth", "Torso depth", 220.0),
        ("ShoulderHeight", "Shoulder center height", 1180.0),
        ("HipHeight", "Hip center height", 800.0),
        ("KneeHeight", "Knee center height", 485.0),
        ("AnkleHeight", "Ankle center height", 120.0),
        ("EStopHeight", "Rear E-stop center height", 1195.0),
    ]:
        p.addProperty("App::PropertyLength", prop, "Geometry", label)
        setattr(p, prop, value)
    p.addProperty("App::PropertyString", "ModelMaturity", "Documentation")
    p.ModelMaturity = "Architecture CAD — dimensions require load analysis and physical validation"
    p.addProperty("App::PropertyString", "Regeneration", "Documentation")
    p.Regeneration = "Edit values in generate_lamina_v4.py or this object, then rerun the generator"
    return p


def build_master():
    doc = App.newDocument("Lamina_Slender_Biped_v4")
    add_robot_parameters(doc)

    wood = doc.addObject("App::DocumentObjectGroup", "WoodStructure")
    wood.Label = "Laser-cut wooden structure"
    joints = doc.addObject("App::DocumentObjectGroup", "JointHardware")
    joints.Label = "Purchased shafts and joint hardware"
    actuation = doc.addObject("App::DocumentObjectGroup", "Actuation")
    actuation.Label = "Purchased actuator envelopes"
    tendons = doc.addObject("App::DocumentObjectGroup", "TendonRouting")
    tendons.Label = "Concept tendon routing"
    sensors = doc.addObject("App::DocumentObjectGroup", "Sensors")
    safety = doc.addObject("App::DocumentObjectGroup", "Safety")
    safety.Label = "Independent safety hardware"

    # Feet and rubber contact surfaces.
    for side, x in [("Left", -105), ("Right", 105)]:
        foot = Part.makeBox(155, 260, 48, App.Vector(x - 77.5, -105, 35))
        toe = Part.makeBox(155, 70, 34, App.Vector(x - 77.5, -175, 42))
        add_feature(doc, wood, side + "Foot", side + " laminated plywood foot", foot.fuse(toe), WOOD_LIGHT)
        sole = Part.makeBox(165, 280, 12, App.Vector(x - 82.5, -185, 23))
        add_feature(doc, sensors, side + "Sole", side + " rubber sole and force-pad envelope", sole, RUBBER)

    # Tapered hollow leg links.
    for side, x in [("Left", -105), ("Right", 105)]:
        add_feature(doc, wood, side + "Shin", side + " hollow shin torsion box", hollow_tapered_link(x, 0, 145, 455, 62, 78, 84, 98), WOOD)
        add_feature(doc, wood, side + "Thigh", side + " hollow thigh torsion box", hollow_tapered_link(x, 0, 515, 770, 82, 95, 108, 118), WOOD)
        add_joint(doc, wood, joints, actuation, side + "Ankle", x, 0, 120, 38, 82)
        add_joint(doc, wood, joints, actuation, side + "Knee", x, 0, 485, 48, 96)
        add_joint(doc, wood, joints, actuation, side + "HipPitch", x, 0, 800, 54, 116)
        # Roll/yaw envelope at hip, shown as a second orthogonal cartridge.
        add_feature(doc, actuation, side + "HipCrossAxis", side + " hip roll/yaw actuator envelope", cylinder_x(x, 0, 800, 34, 95), CHARCOAL)

    # Pelvis and waist.
    add_feature(doc, wood, "Pelvis", "Hollow plywood pelvis motor housing", hollow_box(0, 0, 760, 310, 210, 125, 12), WOOD)
    add_feature(doc, actuation, "PelvisMotorBank", "Lower-body proximal motor bank envelope", Part.makeBox(210, 125, 82, App.Vector(-105, -62.5, 782)), CHARCOAL)
    add_feature(doc, wood, "Waist", "Three-axis wooden waist housing", ellipse_ring(0, 0, 890, 105, 82, 28, 25), WOOD_LIGHT)
    add_feature(doc, actuation, "WaistActuatorEnvelope", "Waist actuator envelope", Part.makeCylinder(62, 62, App.Vector(0, 0, 895)), CHARCOAL)

    # Structural spine and sculptural torso ribs.
    add_feature(doc, wood, "CentralSpine", "Laminated plywood spine torsion box", hollow_box(0, 12, 910, 92, 90, 310, 12), WOOD_EDGE)
    rib_count = 13
    for i in range(rib_count):
        z = 930 + i * 23
        t = i / (rib_count - 1)
        rx = 150 + 55 * math.sin(math.pi * t)
        ry = 88 + 23 * math.sin(math.pi * t)
        add_feature(doc, wood, "TorsoRib%02d" % i, "Torso contour rib %02d" % i, ellipse_ring(0, 0, z, rx, ry, 6, 24), WOOD_LIGHT)

    # Proximal torso motor bank.
    for row in range(3):
        for col in range(4):
            x = -72 + col * 48
            z = 980 + row * 72
            motor = cylinder_y(x, 10, z, 17, 82)
            add_feature(doc, actuation, "TorsoMotor_%d_%d" % (row, col), "Proximal tendon motor", motor, CHARCOAL)

    # Arms and joint cartridges.
    for side, x in [("Left", -245), ("Right", 245)]:
        add_feature(doc, wood, side + "UpperArm", side + " hollow upper-arm torsion box", hollow_tapered_link(x, 0, 930, 1145, 58, 72, 76, 88), WOOD)
        add_feature(doc, wood, side + "Forearm", side + " hollow forearm torsion box", hollow_tapered_link(x, -4, 680, 885, 52, 68, 64, 80), WOOD)
        add_joint(doc, wood, joints, actuation, side + "Shoulder", x, 0, 1180, 52, 100)
        add_joint(doc, wood, joints, actuation, side + "Elbow", x, 0, 905, 39, 82)
        add_joint(doc, wood, joints, actuation, side + "Wrist", x, -4, 655, 29, 66)
        # Palm and three underactuated fingers in a relaxed open pose.
        palm = Part.makeBox(74, 35, 78, App.Vector(x - 37, -20, 560))
        add_feature(doc, wood, side + "Palm", side + " adaptive gripper palm", palm, WOOD_LIGHT)
        for finger_i, dx in enumerate((-25, 0, 25)):
            finger = Part.makeBox(15, 22, 82, App.Vector(x + dx - 7.5, -18, 478))
            add_feature(doc, wood, side + "Finger%d" % finger_i, side + " underactuated finger", finger, WOOD_LIGHT)
            pad = Part.makeBox(15, 7, 38, App.Vector(x + dx - 7.5, -25, 490))
            add_feature(doc, sensors, side + "FingerPad%d" % finger_i, side + " gripper pad", pad, RUBBER)

    # Neck and layered head.
    add_feature(doc, actuation, "Neck", "Two-axis neck actuator envelope", Part.makeCylinder(38, 72, App.Vector(0, 0, 1245)), CHARCOAL)
    for i in range(8):
        z = 1320 + i * 18
        profile = math.sin(math.pi * (i + 1) / 9)
        rx = 65 + 28 * profile
        ry = 58 + 20 * profile
        add_feature(doc, wood, "HeadRib%02d" % i, "Head contour rib %02d" % i, ellipse_ring(0, -3, z, rx, ry, 6, 18), WOOD_LIGHT)
    # Front camera apertures, front is negative Y.
    for x in (-28, 28):
        camera = Part.makeCylinder(9, 12, App.Vector(x, -82, 1390), App.Vector(0, -1, 0))
        add_feature(doc, sensors, "Camera%s" % ("L" if x < 0 else "R"), "Depth camera aperture", camera, CHARCOAL)

    # Tendon routing envelopes from proximal motor banks to distal joints.
    cable_routes = [
        ((-55, 35, 1130), (-245, 28, 905)),
        ((55, 35, 1130), (245, 28, 905)),
        ((-55, 28, 1030), (-245, 20, 655)),
        ((55, 28, 1030), (245, 20, 655)),
        ((-62, 30, 815), (-105, 24, 485)),
        ((62, 30, 815), (105, 24, 485)),
        ((-45, 24, 790), (-105, 20, 120)),
        ((45, 24, 790), (105, 20, 120)),
    ]
    for i, (p0, p1) in enumerate(cable_routes):
        add_feature(doc, tendons, "Tendon%02d" % i, "Concept tendon route %02d" % i, cylinder_between(p0, p1, 3.0), RUBBER)

    # Rear shoulder-level emergency stop: rear is positive Y.
    backing = Part.makeBox(96, 12, 82, App.Vector(-48, 112, 1154))
    add_feature(doc, safety, "EStopBacking", "Fixed rear E-stop backing plate", backing, CHARCOAL)
    collar = Part.makeCylinder(32, 10, App.Vector(0, 124, 1195), App.Vector(0, 1, 0))
    add_feature(doc, safety, "EStopCollar", "E-stop yellow location collar", collar, YELLOW)
    button = Part.makeCylinder(24, 27, App.Vector(0, 134, 1195), App.Vector(0, 1, 0))
    add_feature(doc, safety, "EStopButton", "Rear shoulder-height latching E-stop", button, RED)
    # Separate tether anchor above the E-stop.
    anchor_post = Part.makeCylinder(8, 44, App.Vector(0, 72, 1260), App.Vector(0, 1, 0))
    anchor_ring = Part.makeTorus(27, 7, App.Vector(0, 118, 1280), App.Vector(1, 0, 0), 0, 360, 360)
    add_feature(doc, safety, "TetherAnchor", "Independent upper-spine tether anchor", anchor_post.fuse(anchor_ring), STEEL)

    # Reference floor and human-scale envelope.
    refs = doc.addObject("App::DocumentObjectGroup", "References")
    floor = Part.makeBox(900, 700, 8, App.Vector(-450, -300, 0))
    add_feature(doc, refs, "Floor", "Reference floor", floor, (0.78, 0.78, 0.75), 75)

    doc.recompute()
    master_path = os.path.join(OUT, "Lamina-Slender-Biped-v4.FCStd")
    doc.saveAs(master_path)
    export_objects = [o for o in solid_features(doc) if o.Name != "Floor"]
    Part.export(export_objects, os.path.join(OUT, "Lamina-Slender-Biped-v4.step"))
    return doc


def save_component_document(name, label, pieces):
    doc = App.newDocument(name)
    group = doc.addObject("App::DocumentObjectGroup", "Component")
    group.Label = label
    for piece_name, piece_label, shape, color in pieces:
        add_feature(doc, group, piece_name, piece_label, shape, color)
    note = doc.addObject("App::FeaturePython", "MaturityNote")
    note.addProperty("App::PropertyString", "Status")
    note.Status = "Concept component — validate loads clearances wear and manufacturing tolerances"
    doc.recompute()
    path = os.path.join(OUT, name + ".FCStd")
    doc.saveAs(path)
    export_objects = solid_features(doc)
    Part.export(export_objects, os.path.join(OUT, name + ".step"))
    return doc


def build_component_library():
    save_component_document(
        "Lamina-Hollow-Torsion-Link-v1",
        "Laser-cut hollow tapered link",
        [("Link", "Tapered plywood torsion-box envelope", hollow_tapered_link(0, 0, 0, 320, 62, 78, 92, 108), WOOD)],
    )
    palm = Part.makeBox(78, 38, 85, App.Vector(-39, -19, 0))
    pieces = [("Palm", "Adaptive gripper palm", palm, WOOD_LIGHT)]
    for i, x in enumerate((-27, 0, 27)):
        pieces.append(("Finger%d" % i, "Underactuated finger %d" % (i + 1), Part.makeBox(16, 24, 90, App.Vector(x - 8, -18, -90)), WOOD_LIGHT))
        pieces.append(("Pad%d" % i, "Compliant contact pad %d" % (i + 1), Part.makeBox(16, 7, 42, App.Vector(x - 8, -25, -72)), RUBBER))
    save_component_document("Lamina-Adaptive-Gripper-v1", "Three-finger adaptive gripper envelope", pieces)

    backing = Part.makeBox(96, 12, 82, App.Vector(-48, 0, -41))
    collar = Part.makeCylinder(32, 10, App.Vector(0, 12, 0), App.Vector(0, 1, 0))
    button = Part.makeCylinder(24, 27, App.Vector(0, 22, 0), App.Vector(0, 1, 0))
    anchor = Part.makeTorus(27, 7, App.Vector(0, 45, 95), App.Vector(1, 0, 0), 0, 360, 360)
    save_component_document(
        "Lamina-Rear-Safety-Module-v1",
        "Rear shoulder E-stop and separate tether anchor",
        [
            ("Backing", "Fixed plywood-independent backing", backing, CHARCOAL),
            ("Collar", "Yellow E-stop collar", collar, YELLOW),
            ("Button", "Latching mushroom E-stop", button, RED),
            ("TetherAnchor", "Separate tether anchor", anchor, STEEL),
        ],
    )

    rib = ellipse_ring(0, 0, 0, 200, 110, 6, 24)
    save_component_document(
        "Lamina-Torso-Rib-v1",
        "Replaceable torso contour rib",
        [("TorsoRib", "Six-millimeter replaceable torso rib", rib, WOOD_LIGHT)],
    )


if __name__ == "__main__":
    build_master()
    build_component_library()
    print("Generated Lamina FreeCAD artifacts in: %s" % OUT)
